const man = [
  {
    id: 1,
    name: 'Куртка из двух материалов',
    category: 'jacket',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Голубой'],
    count: 2500,
    coment: [],
    img: ['kurtka-iz-dvukh-materialov-goluboj-muzhchiny-s-xxl-xp331_1_lpr1.webp', 'kurtka-iz-dvukh-materialov-goluboj-muzhchiny-s-xxl-xp331_1_lpr2.webp', 'kurtka-iz-dvukh-materialov-goluboj-muzhchiny-s-xxl-xp331_1_lpr3.webp'],
  },
  {
    id: 2,
    name: 'Парка с капюшоном в стиле пуховика',
    category: 'jacket',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Хаки'],
    count: 3700,
    coment: [],
    img: ['parka-s-kapyushonom-v-stile-pukhovika-khaki-muzhchiny-s-xxl-xp340_3_lpr2.webp', 'parka-s-kapyushonom-v-stile-pukhovika-khaki-muzhchiny-s-xxl-xp340_3_frf5.webp', 'parka-s-kapyushonom-v-stile-pukhovika-khaki-muzhchiny-s-xxl-xp340_3_frf3.webp'],
  },
  {
    id: 3,
    name: 'Джинсовая куртка',
    category: 'jacket',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Серый'],
    count: 1700,
    coment: [],
    img: ['dzhinsovaya-kurtka-seryj-muzhchiny-s-xxl-xd216_1_frf1.webp', 'dzhinsovaya-kurtka-seryj-muzhchiny-s-xxl-xd216_1_frf6.webp', 'dzhinsovaya-kurtka-seryj-muzhchiny-s-xxl-xd216_1_frm.webp'],
  },
  {
    id: 4,
    name: 'Куртка из твила на основе хлопка',
    category: 'jacket',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Голубой'],
    count: 1200,
    coment: [],
    img: ['kurtka-iz-tvila-na-osnove-khlopka-goluboj-muzhchiny-s-xxl-xg714_1_frf1.webp', 'kurtka-iz-tvila-na-osnove-khlopka-goluboj-muzhchiny-s-xxl-xg714_1_frf3.webp', 'kurtka-iz-tvila-na-osnove-khlopka-goluboj-muzhchiny-s-xxl-xg714_1_frf6.webp'],
  },
  {
    id: 5,
    name: 'Облегающие джинсы из хлопка',
    category: 'jeans',
    size: [42, 44, 46, 48, 50, 52],
    color: ['Белый'],
    count: 1300,
    coment: [],
    img: ['oblegayushie-dzhinsy-iz-khlopka-belyj-muzhchiny-s-xxl-vr686_13_frf1.webp', 'oblegayushie-dzhinsy-iz-khlopka-belyj-muzhchiny-s-xxl-vr686_13_frf5.webp'],
  },
  {
    id: 6,
    name: 'Узкие джинсы с выбеленным эффектом',
    category: 'jeans',
    size: [42, 44, 46, 48, 50, 52],
    color: ['Голубой'],
    count: 2100,
    coment: [],
    img: ['uzkie-dzhinsy-s-vybelennym-effektom-goluboj-muzhchiny-s-xxl-xg462_1_frf1.webp', 'uzkie-dzhinsy-s-vybelennym-effektom-goluboj-muzhchiny-s-xxl-xg462_1_frf2.webp'],
  },
  {
    id: 7,
    name: 'Джинсы стандартного кроя',
    category: 'jeans',
    size: [42, 44, 46, 48, 50, 52],
    color: ['Серый'],
    count: 2100,
    coment: [],
    img: ['dzhinsy-standartnogo-kroya-goluboj-muzhchiny-s-xxl-xq041_3_frf1.webp', 'dzhinsy-standartnogo-kroya-goluboj-muzhchiny-s-xxl-xq041_3_frf2.webp', 'dzhinsy-standartnogo-kroya-goluboj-muzhchiny-s-xxl-xq041_3_frf3.webp'],
  },
  {
    id: 8,
    name: 'Зауженные джинсы из эластичного хлопка L32',
    category: 'jeans',
    size: [58, 60, 62, 64, 66, 68],
    color: ['Синий индиго'],
    count: 1700,
    coment: [],
    img: ['zauzhennye-dzhinsy-iz-elastichnogo-khlopka-l32-sinij-indigo-muzhchiny-bolshie-razmery-wp147_1_frf1.webp', 'zauzhennye-dzhinsy-iz-elastichnogo-khlopka-l32-sinij-indigo-muzhchiny-bolshie-razmery-wp147_1_frf3.webp'],
  },
  {
    id: 9,
    name: 'Футболка Eco-conception c флагом',
    category: 'undershirt',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Белый'],
    count: 500,
    coment: [],
    img: ['futbolka-eco-conception-c-flagom-belyj-muzhchiny-s-xxl-xo531_2_frf1.webp', 'futbolka-eco-conception-c-flagom-belyj-muzhchiny-s-xxl-xo531_2_frf4.webp'],
  },
  {
    id: 10,
    name: 'Текстурная футболка Eco-conception',
    category: 'undershirt',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Красно-оранжевый'],
    count: 700,
    coment: [],
    img: ['futbolka-eco-conception-serfer-krasnyj-muzhchiny-s-xxl-xo531_12_frf1.webp', 'futbolka-eco-conception-serfer-krasnyj-muzhchiny-s-xxl-xo531_12_frf3.webp'],
  },
  {
    id: 11,
    name: "Футболка Eco-conception 'The Boss'",
    category: 'undershirt',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Белый'],
    count: 350,
    coment: [],
    img: ['futbolka-eco-conception-the-boss-belyj-muzhchiny-s-xxl-xt255_8_frf1.webp', 'futbolka-eco-conception-the-boss-belyj-muzhchiny-s-xxl-xt255_8_frf2.webp'],
  },
  {
    id: 12,
    name: "Футболка Eco-conception 'Ворчун'",
    category: 'undershirt',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Голубой'],
    count: 350,
    coment: [],
    img: ['futbolka-eco-conception-vorchun-goluboj-muzhchiny-s-xxl-xt255_6_frf1.webp', 'futbolka-eco-conception-vorchun-goluboj-muzhchiny-s-xxl-xt255_6_frf3.webp'],
  },
  {
    id: 13,
    name: 'Спортивные шорты из мольтона',
    category: 'sport',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Черный'],
    count: 990,
    coment: [],
    img: ['sportivnye-shorty-iz-moltona-chernyj-muzhchiny-s-xxl-xg609_1_frf1.webp', 'sportivnye-shorty-iz-moltona-chernyj-muzhchiny-s-xxl-xg609_1_frf2.webp', 'sportivnye-shorty-iz-moltona-chernyj-muzhchiny-s-xxl-xg609_1_frf3.webp', 'sportivnye-shorty-iz-moltona-chernyj-muzhchiny-s-xxl-xg609_1_frf6.webp'],
  },
  {
    id: 14,
    name: '',
    category: 'sport',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Черный'],
    count: 1500,
    coment: [],
    img: ['sportivnye-bryuki-chernyj-muzhchiny-s-xxl-xp909_2_frf1.webp', 'sportivnye-bryuki-chernyj-muzhchiny-s-xxl-xp909_2_frf2.webp'],
  },
  {
    id: 15,
    name: "Ветровка колор-блок 'Eco-conception'",
    category: 'sport',
    size: ['S', 'M', 'L', 'XL', 'XXL'],
    color: ['Голубой'],
    count: 2000,
    coment: [],
    img: ['vetrovka-kolor-blok-eco-conception-goluboj-muzhchiny-s-xxl-xg165_1_frf4.webp', 'vetrovka-kolor-blok-eco-conception-goluboj-muzhchiny-s-xxl-xg165_1_frf5.webp', 'vetrovka-kolor-blok-eco-conception-goluboj-muzhchiny-s-xxl-xg165_1_frf1.webp'],
  },

];
const woman = [
  {
    id: 16,
    name: 'Длинное пальто из материала под шерсть',
    category: 'jacket',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Зеленый'],
    count: 3200,
    coment: [],
    img: ['dlinnoe-palto-iz-materiala-pod-sherst-zelenyj-zhenshiny-razmery-40-54-xr458_1_frf1.webp', 'dlinnoe-palto-iz-materiala-pod-sherst-zelenyj-zhenshiny-razmery-40-54-xr458_1_frf2.webp', 'dlinnoe-palto-iz-materiala-pod-sherst-zelenyj-zhenshiny-razmery-40-54-xr458_1_frf5.webp'],
  },
  {
    id: 17,
    name: 'Куртка в байкерском стиле',
    category: 'jacket',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Коричневый'],
    count: 2800,
    coment: [],
    img: ['kurtka-v-bajkerskom-stile-korichnevyj-bolshie-razmery-xo564_4_frf1.webp', 'kurtka-v-bajkerskom-stile-korichnevyj-bolshie-razmery-xo564_4_frf4.webp', 'kurtka-v-bajkerskom-stile-korichnevyj-bolshie-razmery-xo564_4_frf2.webp'],
  },
  {
    id: 18,
    name: 'Длинный пуховик из водоотталкивающего материала',
    category: 'jacket',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Черный'],
    count: 4300,
    coment: [],
    img: ['dlinnyj-pukhovik-iz-vodoottalkivayushego-materiala-chernyj-bolshie-razmery-xr616_1_frf1.webp', 'dlinnyj-pukhovik-iz-vodoottalkivayushego-materiala-chernyj-bolshie-razmery-xr616_1_frf5.webp', 'dlinnyj-pukhovik-iz-vodoottalkivayushego-materiala-chernyj-bolshie-razmery-xr616_1_frf2.webp', 'dlinnyj-pukhovik-iz-vodoottalkivayushego-materiala-chernyj-bolshie-razmery-xr616_1_frf3.webp'],
  },
  {
    id: 19,
    name: 'Куртка-сафари',
    category: 'jacket',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Хаки'],
    count: 2300,
    coment: [],
    img: ['kurtka-safari-khaki-zhenshiny-razmery-40-54-xe236_1_frf1.webp', 'kurtka-safari-khaki-zhenshiny-razmery-40-54-xe236_1_frf2.webp', 'kurtka-safari-khaki-zhenshiny-razmery-40-54-xe236_1_frf3.webp'],
  },
  {
    id: 20,
    name: 'Облегающие джинсы Eco-conception',
    category: 'jeans',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Джинсовый'],
    count: 800,
    coment: [],
    img: ['oblegayushie-dzhinsy-eco-conception-dzhinsovyj-zhenshiny-razmery-40-54-tn785_3_frf1.webp', 'oblegayushie-dzhinsy-eco-conception-dzhinsovyj-zhenshiny-razmery-40-54-tn785_3_frf4.webp', 'oblegayushie-dzhinsy-eco-conception-dzhinsovyj-zhenshiny-razmery-40-54-tn785_3_frf5.webp'],
  },
  {
    id: 21,
    name: ' Джинсы с высокой посадкой',
    category: 'jeans',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Голубой'],
    count: 1500,
    coment: [],
    img: ['dzhinsy-s-vysokoj-posadkoj-goluboj-zhenshiny-razmery-40-54-xt765_1_frf1.webp', 'dzhinsy-s-vysokoj-posadkoj-goluboj-zhenshiny-razmery-40-54-xt765_1_frf2.webp', 'dzhinsy-s-vysokoj-posadkoj-goluboj-zhenshiny-razmery-40-54-xt765_1_frf4.webp'],
  },
  {
    id: 22,
    name: 'Джеггинсы с высокой талией',
    category: 'jeans',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Темно синий'],
    count: 800,
    coment: [],
    img: ['dzhegginsy-s-vysokoj-taliej-temno-sinij-zhenshiny-razmery-40-54-te035_3_frf1.webp', 'dzhegginsy-s-vysokoj-taliej-temno-sinij-zhenshiny-razmery-40-54-te035_3_frf2.webp', 'dzhegginsy-s-vysokoj-taliej-temno-sinij-zhenshiny-razmery-40-54-te035_3_frf4.webp'],
  },
  {
    id: 24,
    name: 'Джинсы стандартного кроя',
    category: 'jeans',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Бежевый'],
    count: 1700,
    coment: [],
    img: ['dzhinsy-standartnogo-kroya-bezhevyj-zhenshiny-razmery-40-54-xk963_1_frf1.webp', 'dzhinsy-standartnogo-kroya-bezhevyj-zhenshiny-razmery-40-54-xk963_1_frf2.webp', 'dzhinsy-standartnogo-kroya-bezhevyj-zhenshiny-razmery-40-54-xk963_1_frf3.webp'],
  },
  {
    id: 23,
    name: 'Футболка из трикотажа в рубчик',
    category: 'undershirt',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Белый'],
    count: 990,
    coment: [],
    img: ['futbolka-iz-trikotazha-v-rubchik-snezhno-belyj-zhenshiny-razmery-40-54-xx438_1_frf1.webp', 'futbolka-iz-trikotazha-v-rubchik-snezhno-belyj-zhenshiny-razmery-40-54-xx438_1_frf3.webp', 'futbolka-iz-trikotazha-v-rubchik-snezhno-belyj-zhenshiny-razmery-40-54-xx438_1_frf4.webp'],
  },
  {
    id: 25,
    name: "disney Футболка 'Минни Маус'",
    category: 'undershirt',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Белый'],
    count: 750,
    coment: [],
    img: ['futbolka-minni-maus-belyj-zhenshiny-razmery-40-54-xs159_12_frf1.webp', 'futbolka-minni-maus-belyj-zhenshiny-razmery-40-54-xs159_12_frf3.webp'],
  },
  {
    id: 26,
    name: 'Тонкий джемпер с кружевными деталями',
    category: 'undershirt',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Сапфир'],
    count: 1100,
    coment: [],
    img: ['tonkij-dzhemper-s-kruzhevnymi-detalyami-sapfir-zhenshiny-razmery-40-54-xn386_2_frf1.webp', 'tonkij-dzhemper-s-kruzhevnymi-detalyami-sapfir-zhenshiny-razmery-40-54-xn386_2_frf3.webp'],
  },
  {
    id: 27,
    name: 'Футболка с присобранной горловиной',
    category: 'undershirt',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Бежевый'],
    count: 990,
    coment: [],
    img: ['futbolka-s-prisobrannoj-gorlovinoj-chernyj-zhenshiny-razmery-40-54-xn377_1_frf1.webp', 'futbolka-s-prisobrannoj-gorlovinoj-chernyj-zhenshiny-razmery-40-54-xn377_1_frf3.webp'],
  },
  {
    id: 28,
    name: 'Бюстгальтер со спинкой-борцовкой',
    category: 'sport',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Черный'],
    count: 1100,
    coment: [],
    img: ['byustgalter-so-spinkoj-bortsovkoj-chernyj-zhenskoe-belje-razmery-s-xxl-vt796_2_frf1.webp', 'byustgalter-so-spinkoj-bortsovkoj-chernyj-zhenskoe-belje-razmery-s-xxl-vt796_2_frf2.webp'],
  },
  {
    id: 29,
    name: 'Спортивные шорты из мольтона',
    category: 'sport',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Черный'],
    count: 400,
    coment: [],
    img: ['sportivnye-shorty-iz-moltona-chernyj-zhenshiny-razmery-40-54-xf109_2_frf1.webp', 'sportivnye-shorty-iz-moltona-chernyj-zhenshiny-razmery-40-54-xf109_2_frf2.webp'],
  },
  {
    id: 30,
    name: 'Спортивные брюки-капри',
    category: 'sport',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['Черный'],
    count: 650,
    coment: [],
    img: ['sportivnye-bryuki-kapri-chernyj-zhenshiny-razmery-40-54-xd359_1_frf1.webp', 'sportivnye-bryuki-kapri-chernyj-zhenshiny-razmery-40-54-xd359_1_frf3.webp'],
  },
];
